config/routes.rb
TwitterApp::Application.routes.draw do

  resources :raillers

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  resources :users

    root to: 'users#new'

end

app/models/railler.rb
class Railler < ActiveRecord::Base

has_many :raillers

	default_scope order: 'createdat DESC'
  attr_accessible :content, :userid
  belongs_to :user

  validates :content, length: { maximum: 140 }
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	before_validation :prep_email
	before_save :create_avatar_url

	has_secure_password
	validates :name, presence: true
	validates :username, uniqueness: true, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

end

def create_avatar_url
    self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
end

private

def prep_email
    self.email = self.email.strip.downcase if self.email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user

end

app/controllers/raillers_controller.rb
class RaillersController < ApplicationController

	def create
		@railler = Raille.new(params[:railler])
		@railler.userid = current_user.id</p>

		if @railler.save
		  redirect_to current_user 
		else
		  flash[:error] = "Problem!"
		  redirect_to current_user
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
        session[:userid] = user.id
        redirect_to rooturl, notice: "Logged in!"
    else
        flash[:error] = "Wrong Username or Password."
        redirect_to root_url
    end
  end

  def destroy
 	session[:userid] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
	end
	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	  	 session[:user_id] = @user.id
	    redirect_to @user, notice: "Thank you for signing up for Railler!"
	  else
	    render 'new'
	  end
	end

	def show
	  @user = User.find(params[:id])
        @railler = Railler.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raillers_helper.rb
module RaillersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
    <head>
        <link rel="stylesheet/less" href="/style.less">
        <script src="/less.js"></script>
    </head>
    <body>
        <header>
            <div class="wrapper">
                <!-- <img src="/gfx/logo.png"> -->
                <span>Twitter Clone</span>
                <% if current_user %>
        <%= link_to "Log Out", sessions_destroy_path %>
    <% else %>
        <%= form_tag sessions_create_path do %>
            <%= text_field_tag :username, nil, placeholder: "username" %>
            <%= password_field_tag :password, nil,  placeholder: "password" %>
            <%= submit_tag "Log In" %>
        <% end %>
    <% end %>
            </div>
        </header>
        <div id="content">
            <div class="wrapper">
                <% flash.each do |name, msg| %>
                    <%= content_tag :div, msg, class: "flash #{name}" %>
                <% end %>
                <%= yield %>
            </div>
        </div>
        <footer>
            <div class="wrapper">
                Railler - A Twitter Clone <!-- <img src="/gfx/logo-nettuts.png"> -->
            </div>
        </footer>
    </body>
    </html>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg">

<div class="panel right">
  <h1>New to Railler?</h1>
  
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.text_field :email, placeholder: "email" %>
    <%= f.text_field :username, placeholder: "username" %>
    <%= f.text_field :name, placeholder: "name" %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.password_field :password_confirmation, placeholder: "password" %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% if current_user %>
    <div id="createRailler" class="panel right">
        <h1>Create a Railler</h1>
        <p>
        <%= form_for @railler do |f| %>
            <%= f.textarea :content, class: 'raillerText' %>
            <%= f.submit "Railler!" %>
        <% end %>
        </p>
    </div>
    <% end %>
    <div id="railler" class="panel left">
        <h1>Your Railler Profile</h1>
        <div class="raillerWrapper">
            <img class="avatar" src="<%= @user.avatar_url %>">
            <span class="name"><%= @user.name %></span> @<%= @user.username %>
            <p>
            <%= @user.railler.size %> Raillers
            <span class="spacing">XX Followers</span>
            <span class="spacing">XX Following</span>
            </p>
        </div>
    </div>
    <div class="panel left">
        <h1>Your Railler</h1>
        <% @user.railler.each do |ribbit| %>
            <div class="raillerWrapper">
                <img class="avatar" src="<%= @user.avatar_url %>">
                <span class="name"><%= @user.name %></span> 
                @<%= @user.username %> 
                <span class="time"><%= time_ago_in_words(railler.created_at) %></span>
                <p> <%= railler.content %> </p>
            </div>
        <% end %>
    </div>